<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employment extends Model
{
    protected $fillable = [
        'trainee_id',
        'company_name',
        'position_title',
        'job_description',
        'employment_date',
        'status',
        'notes',
        'contact_person',
        'contact_email',
        'contact_phone',
        'salary_range',
        'employment_type',
        'is_auto_generated',
        'assessment_id',
    ];

    protected $casts = [
        'employment_date' => 'date',
        'is_auto_generated' => 'boolean',
    ];

    /**
     * Get the trainee associated with the employment
     */
    public function trainee()
    {
        return $this->belongsTo(Trainee::class);
    }

    /**
     * Get the assessment that triggered this employment record
     */
    public function assessment()
    {
        return $this->belongsTo(Assessment::class);
    }

    /**
     * Scope to get only auto-generated employments
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope to get only manually created employments
     */
    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }
}
